### ISSUE TITLE
How to implement GradCAM on vgg16?

### ISSUE THREAD

**Issue by lantuxin** [bardiadoosti/GradCAM-PyCaffe#2]
I trained a vgg16 model with py-faster-rcnn, but I don't know to how to implement GradCAM on my vgg16 model. Can you give me some suggestions? Thank you!

**Comment by bardiadoosti** [comment]
Hi,

GradCAM (Unlike CAM) does not relate on the architecture of your network. All you need to set is the name of the last layer ('fc8' in AlexNet) and the interest convolutional layer ('conv5' in AlexNet') in the code.
